"""add user search engine

Revision ID: 31d25ffbf143
Revises: 0e7931683f15
Create Date: 2026-08-24 14:00:41.587397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31d25ffbf143'
down_revision: Union[str, None] = '0e7931683f15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('search_engine', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'search_engine')
    # ### end Alembic commands ###
