"""add categories and tile size

Revision ID: 76f47c7a8689
Revises: 80a2f994f927
Create Date: 2026-08-23 18:58:33.873681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76f47c7a8689'
down_revision: Union[str, None] = '80a2f994f927'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dashboard_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dashboard_id'], ['dashboards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # batch mode: SQLite has no ALTER TABLE ADD CONSTRAINT - needed to add category_id + its FK
    # to the pre-existing dashboard_items table (same pattern as the logo_id migration).
    with op.batch_alter_table('dashboard_items') as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_dashboard_items_category_id_categories', 'categories', ['category_id'], ['id'],
            ondelete='SET NULL',
        )
    # server_default so existing dashboard rows get a value - the model's Python-side default
    # only applies to new rows the ORM inserts, not rows that already exist in the DB.
    op.add_column(
        'dashboards',
        sa.Column('tile_size', sa.String(), nullable=False, server_default='medium'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dashboards', 'tile_size')
    with op.batch_alter_table('dashboard_items') as batch_op:
        batch_op.drop_constraint('fk_dashboard_items_category_id_categories', type_='foreignkey')
        batch_op.drop_column('category_id')
    op.drop_table('categories')
    # ### end Alembic commands ###
