"""add logo library

Revision ID: 80a2f994f927
Revises: 883f3e7565a1
Create Date: 2026-08-23 17:48:16.483683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80a2f994f927'
down_revision: Union[str, None] = '883f3e7565a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('keywords', sa.JSON(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # SQLite has no ALTER TABLE ADD CONSTRAINT - batch mode does the copy-and-move dance needed
    # to add a column with a foreign key to an existing table.
    with op.batch_alter_table('guests') as batch_op:
        batch_op.add_column(sa.Column('logo_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_guests_logo_id_logos', 'logos', ['logo_id'], ['id'], ondelete='SET NULL')
    with op.batch_alter_table('proxy_hosts') as batch_op:
        batch_op.add_column(sa.Column('logo_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_proxy_hosts_logo_id_logos', 'logos', ['logo_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proxy_hosts') as batch_op:
        batch_op.drop_constraint('fk_proxy_hosts_logo_id_logos', type_='foreignkey')
        batch_op.drop_column('logo_id')
    with op.batch_alter_table('guests') as batch_op:
        batch_op.drop_constraint('fk_guests_logo_id_logos', type_='foreignkey')
        batch_op.drop_column('logo_id')
    op.drop_table('logos')
    # ### end Alembic commands ###
