"""initial schema

Revision ID: 883f3e7565a1
Revises: 
Create Date: 2026-08-23 16:25:16.841840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '883f3e7565a1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dashboards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_dashboard_single_default', 'dashboards', ['is_default'], unique=True, sqlite_where=sa.text('is_default'))
    op.create_table('guests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node', sa.String(), nullable=False),
    sa.Column('vmid', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('cpu', sa.Float(), nullable=True),
    sa.Column('mem', sa.Integer(), nullable=True),
    sa.Column('maxmem', sa.Integer(), nullable=True),
    sa.Column('ip_addresses', sa.JSON(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('node', 'vmid', name='uq_guest_node_vmid')
    )
    op.create_table('proxy_hosts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('npm_host_id', sa.Integer(), nullable=False),
    sa.Column('domain_names', sa.JSON(), nullable=False),
    sa.Column('forward_scheme', sa.String(), nullable=False),
    sa.Column('forward_host', sa.String(), nullable=False),
    sa.Column('forward_port', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('online', sa.Boolean(), nullable=True),
    sa.Column('ssl', sa.Boolean(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proxy_hosts_npm_host_id'), 'proxy_hosts', ['npm_host_id'], unique=True)
    op.create_table('dashboard_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dashboard_id', sa.Integer(), nullable=False),
    sa.Column('proxy_host_id', sa.Integer(), nullable=True),
    sa.Column('guest_id', sa.Integer(), nullable=True),
    sa.Column('visible', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('display_name_override', sa.String(), nullable=True),
    sa.CheckConstraint('(proxy_host_id IS NOT NULL AND guest_id IS NULL) OR (proxy_host_id IS NULL AND guest_id IS NOT NULL)', name='ck_dashboard_item_exactly_one_target'),
    sa.ForeignKeyConstraint(['dashboard_id'], ['dashboards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proxy_host_id'], ['proxy_hosts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dashboard_id', 'guest_id', name='uq_dashboard_item_guest'),
    sa.UniqueConstraint('dashboard_id', 'proxy_host_id', name='uq_dashboard_item_proxy_host')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('dashboard_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dashboard_id'], ['dashboards.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('oidc_identities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'subject', name='uq_oidc_provider_subject')
    )
    op.create_table('sessions',
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('csrf_token', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token_hash')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sessions')
    op.drop_table('oidc_identities')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('dashboard_items')
    op.drop_index(op.f('ix_proxy_hosts_npm_host_id'), table_name='proxy_hosts')
    op.drop_table('proxy_hosts')
    op.drop_table('guests')
    op.drop_index('uq_dashboard_single_default', table_name='dashboards', sqlite_where=sa.text('is_default'))
    op.drop_table('dashboards')
    # ### end Alembic commands ###
